/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 plant.gltf --transform 
Files: plant.gltf [5.89MB] > C:\Users\mudar\Downloads\plant3d\plant-transformed.glb [477.76KB] (92%)
Author: laanita (https://sketchfab.com/laanita)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/potted-plant-83986836419445edb3e507b9eb0c786b
Title: Potted Plant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/plant-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder1_lambert3_0.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.pCylinder1_lambert4_0.geometry} material={materials.lambert4} />
      <mesh geometry={nodes.polySurface7_lambert2_0.geometry} material={materials.lambert2} />
    </group>
  )
}

useGLTF.preload('/plant-transformed.glb')
